### ISSUE TITLE
Testimonial and Footer section

### ISSUE THREAD

**Issue by Profsain** [Profsain/HomeFlex-App#5]
Create a Testimonial section on the home page
Create a Footer section of the home page
![f2](https://github.com/Profsain/HomeFlex-App/assets/32632836/73485268-8710-454f-b351-6fdfc2599ee0)
![f1](https://github.com/Profsain/HomeFlex-App/assets/32632836/c401cf3b-a539-4cae-9ea4-049c65b37e35)

**Comment by outstanding01** [comment]
#15
